### ISSUE TITLE
Update Icons / Logos

### ISSUE THREAD

**Issue by xhad** [loreum-org/docs.loreum.org#12]
1. Create an icon set for the site from https://cdn.loreum.org/logos/black.png

( You may need to search for an .ico generator

2. Update the Favicon

3. Update the logo in the config

<img width="779" alt="Screenshot 2023-01-17 at 11 47 45 AM" src="https://user-images.githubusercontent.com/6130115/212960652-efbf16f3-f097-485b-9538-e16de1342eb0.png">

**Comment by pseudonaut** [comment]
Should consider a "Light" and a "Dark" theme logo:

![image](https://user-images.githubusercontent.com/26582141/212962145-9535d0b7-d3f7-42a5-9aeb-74053ebac2ce.png)

![image](https://user-images.githubusercontent.com/26582141/212962195-eaa0112e-d8e9-443c-ae00-4a6a18aa0653.png)

Currently not visible on "Light" theme

**Comment by xhad** [comment]
@pseudonaut thanks for finding this one! @ArnaudBand please take a look on the light theme, the logo doesn't show up. Do you think there is something we can do about that?

https://cdn.loreum.org/logos/black.svg is the logo we need on the light theme

**Comment by ArnaudBand** [comment]
- [x] Update the favicon.
- [x] Add the black logo on the light theme and white on the dark.
- [x] Update the config files by removing unused objects.
- [x] Change the background color for the highlight markdown
