### ISSUE TITLE
Font color Updates for Dark / Light Themes

### ISSUE THREAD

**Issue by xhad** [loreum-org/docs.loreum.org#8]
## Description
It seems the text while in dark mode is black with a black background and it's difficult to read. Here's a screenshot of the issue:

<img width="510" alt="Screenshot 2023-01-14 at 4 00 20 PM" src="https://user-images.githubusercontent.com/6130115/212496676-3aa22859-8697-48e7-9e24-5993825d660b.png">

Also, the 'twitter' link in the footer when the page is in Light mode is white on white and difficult to read. Kindly see if this text can be made black/dark.

<img width="1494" alt="Screenshot 2023-01-14 at 4 02 20 PM" src="https://user-images.githubusercontent.com/6130115/212496739-5bef0948-4d87-4224-b0b4-11bbf17e64c1.png">

**Comment by ArnaudBand** [comment]
I have reviewed the issue  and have completed work on it. Please let me know if you need any additional information or if there are any issues with the changes that need to be addressed.

**Comment by xhad** [comment]
<img width="545" alt="Screenshot 2023-01-14 at 4 49 33 PM" src="https://user-images.githubusercontent.com/6130115/212498601-8b25ce5e-e9eb-49c0-b322-f2a843737376.png">

You can see how the Font for links is black on black.. We need to make the link or secondary text lighter so that it's easier to read.

We have a simple brand guide attached here. Could you please use these colors as secondary colors.
[Loreum Brand Guide 1.pdf](https://github.com/loreum-org/docs.loreum.org/files/10418901/Loreum.Brand.Guide.1.pdf)

**Comment by xhad** [comment]
@ArnaudBand The color scheme that you should use is on the PDG above this message. Please see the colors palette on the pfd and update the secondary colors accordingly.
